"""add receipt exchange fields

Revision ID: 1c5e80784d3c
Revises: 8c70c4998487
Create Date: 2026-09-18 09:33:17.877287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c5e80784d3c'
down_revision: Union[str, Sequence[str], None] = '8c70c4998487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('exchange_rate', sa.Numeric(precision=20, scale=8), nullable=True))
    op.add_column('receipt', sa.Column('converted_total', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('receipt', sa.Column('rate_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt', 'rate_date')
    op.drop_column('receipt', 'converted_total')
    op.drop_column('receipt', 'exchange_rate')
    # ### end Alembic commands ###
