"""add translated name to receipt item

Revision ID: 3f35beab0564
Revises: 1c5e80784d3c
Create Date: 2026-09-18 14:55:45.065155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f35beab0564'
down_revision: Union[str, Sequence[str], None] = '1c5e80784d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_item', sa.Column('translated_name', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt_item', 'translated_name')
    # ### end Alembic commands ###
