"""add merchant_name to receipt

Revision ID: 8c70c4998487
Revises: ab62531c3c9e
Create Date: 2026-09-17 17:35:46.667067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c70c4998487'
down_revision: Union[str, Sequence[str], None] = 'ab62531c3c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_item', sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt_item', 'unit_price')
    # ### end Alembic commands ###
