"""add merchant_name to receipt

Revision ID: ab62531c3c9e
Revises: 3ab5b6082a92
Create Date: 2026-09-17 17:34:57.268386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab62531c3c9e'
down_revision: Union[str, Sequence[str], None] = '3ab5b6082a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt', sa.Column('merchant_name', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt', 'merchant_name')
    # ### end Alembic commands ###
